//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinhro_spr_etran.ServiceEtran {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEtran.SysCISS")]
    public interface SysCISS {
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (nsCISS) сообщения SendBlockRequest не соответствует значению по умолчанию (http://tempuri.org/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:nsCISS", ReplyAction="*")]
        Sinhro_spr_etran.ServiceEtran.SendBlockResponse SendBlock(Sinhro_spr_etran.ServiceEtran.SendBlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:nsCISS", ReplyAction="*")]
        System.Threading.Tasks.Task<Sinhro_spr_etran.ServiceEtran.SendBlockResponse> SendBlockAsync(Sinhro_spr_etran.ServiceEtran.SendBlockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:nsCISS", ReplyAction="*")]
        Sinhro_spr_etran.ServiceEtran.GetBlockResponse GetBlock(Sinhro_spr_etran.ServiceEtran.GetBlockRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="urn:nsCISS", ReplyAction="*")]
        System.Threading.Tasks.Task<Sinhro_spr_etran.ServiceEtran.GetBlockResponse> GetBlockAsync(Sinhro_spr_etran.ServiceEtran.GetBlockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendBlock", WrapperNamespace="nsCISS", IsWrapped=true)]
    public partial class SendBlockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Text;
        
        public SendBlockRequest() {
        }
        
        public SendBlockRequest(string Text) {
            this.Text = Text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendBlockResponse", WrapperNamespace="nsCISS", IsWrapped=true)]
    public partial class SendBlockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public SendBlockResponse() {
        }
        
        public SendBlockResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBlock", WrapperNamespace="nsCISS", IsWrapped=true)]
    public partial class GetBlockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string text;
        
        public GetBlockRequest() {
        }
        
        public GetBlockRequest(string login, string password, string text) {
            this.login = login;
            this.password = password;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBlockResponse", WrapperNamespace="nsCISS", IsWrapped=true)]
    public partial class GetBlockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string text;
        
        public GetBlockResponse() {
        }
        
        public GetBlockResponse(bool @return, string text) {
            this.@return = @return;
            this.text = text;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SysCISSChannel : Sinhro_spr_etran.ServiceEtran.SysCISS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SysCISSClient : System.ServiceModel.ClientBase<Sinhro_spr_etran.ServiceEtran.SysCISS>, Sinhro_spr_etran.ServiceEtran.SysCISS {
        
        public SysCISSClient() {
        }
        
        public SysCISSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SysCISSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysCISSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysCISSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sinhro_spr_etran.ServiceEtran.SendBlockResponse Sinhro_spr_etran.ServiceEtran.SysCISS.SendBlock(Sinhro_spr_etran.ServiceEtran.SendBlockRequest request) {
            return base.Channel.SendBlock(request);
        }
        
        public bool SendBlock(string Text) {
            Sinhro_spr_etran.ServiceEtran.SendBlockRequest inValue = new Sinhro_spr_etran.ServiceEtran.SendBlockRequest();
            inValue.Text = Text;
            Sinhro_spr_etran.ServiceEtran.SendBlockResponse retVal = ((Sinhro_spr_etran.ServiceEtran.SysCISS)(this)).SendBlock(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sinhro_spr_etran.ServiceEtran.SendBlockResponse> Sinhro_spr_etran.ServiceEtran.SysCISS.SendBlockAsync(Sinhro_spr_etran.ServiceEtran.SendBlockRequest request) {
            return base.Channel.SendBlockAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sinhro_spr_etran.ServiceEtran.SendBlockResponse> SendBlockAsync(string Text) {
            Sinhro_spr_etran.ServiceEtran.SendBlockRequest inValue = new Sinhro_spr_etran.ServiceEtran.SendBlockRequest();
            inValue.Text = Text;
            return ((Sinhro_spr_etran.ServiceEtran.SysCISS)(this)).SendBlockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sinhro_spr_etran.ServiceEtran.GetBlockResponse Sinhro_spr_etran.ServiceEtran.SysCISS.GetBlock(Sinhro_spr_etran.ServiceEtran.GetBlockRequest request) {
            return base.Channel.GetBlock(request);
        }
        
        public bool GetBlock(string login, string password, ref string text) {
            Sinhro_spr_etran.ServiceEtran.GetBlockRequest inValue = new Sinhro_spr_etran.ServiceEtran.GetBlockRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.text = text;
            Sinhro_spr_etran.ServiceEtran.GetBlockResponse retVal = ((Sinhro_spr_etran.ServiceEtran.SysCISS)(this)).GetBlock(inValue);
            text = retVal.text;
            return retVal.@return;
        }
        
        public System.Threading.Tasks.Task<Sinhro_spr_etran.ServiceEtran.GetBlockResponse> GetBlockAsync(Sinhro_spr_etran.ServiceEtran.GetBlockRequest request) {
            return base.Channel.GetBlockAsync(request);
        }
    }
}
